FinalProjectasp/FinalProjectasp/Areas/Admin/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalProjectasp.DAL;
using Microsoft.AspNetCore.Mvc;

namespace FinalProjectasp.Areas.Admin.Controllers
{

    [Area("Admin")]
    public class EventController : Controller
    {

       

        private readonly AppDbContext _context;

        public EventController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Events.Where(e => e.IsDeleted == false).ToList());
        }


        public async Task<IActionResult> Create() {


            return View();
        }

        //public async Task<IActionResult> Create(Event event)
        //{
        //    if (!ModelState.IsValid)
        //    {

        //    }

        //    return View();
        //}


    }
}

FinalProjectasp/FinalProjectasp/ViewComponents/FooterViewComponent.cs
using FinalProjectasp.DAL;
using FinalProjectasp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectasp.ViewComponents
{

   
    public class FooterViewComponent : ViewComponent
    {

        private readonly AppDbContext _context;
        public FooterViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            Footer model = _context.Footer.FirstOrDefault();
            return View(await Task.FromResult(model));
        }
    }
}

FinalProjectasp/FinalProjectasp/ViewComponents/HeaderViewComponent.cs
using FinalProjectasp.DAL;
using FinalProjectasp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectasp.ViewComponents
{
    [ViewComponent(Name = "Header")]
    public class HeaderViewComponent: Microsoft.AspNetCore.Mvc.ViewComponent
    {

        private readonly AppDbContext _context;
        public HeaderViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<Microsoft.AspNetCore.Mvc.IViewComponentResult> Invoke()
        {
            Header model = _context.Header.FirstOrDefault();
            return View(await Task.FromResult(model));
        }
    }
}

FinalProjectasp/FinalProjectasp/Views/Shared/_BlogPartial.cshtml
@model List<Blog>;
@{
    Layout = null;
}

@foreach (Blog blog in Model)
{
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="single-blog">
            <div class="blog-img">
                <a href="blog-details.html"><img src="~/img/blog/@blog.Image" alt="blog"></a>
                <div class="blog-hover">
                    <a href="blog-details.html"><i class="fa fa-link"></i></a>
                </div>
            </div>
            <div class="blog-content">
                <div class="blog-top">
                    <p>@blog.Writer /  @blog.Time  /  <i class="fa fa-comments-o"></i> @blog.ReadCount  </p>
                </div>
                <div class="blog-bottom">
                    <h2><a href="blog-details.html">@blog.Title </a></h2>
                    <a href="blog-details.html">read more</a>
                </div>
            </div>
        </div>
    </div>
}

FinalProjectasp/FinalProjectasp/Views/Shared/_CoursePartial.cshtml
@model List<Course>;
@{
    Layout = null;
}

@foreach (Course course in Model)
{
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="single-course">
            <div class="course-img">
                <a href="course-details.html">
                    <img src="~/img/course/@course.Image" alt="course">
                    <div class="course-hover">
                        <i class="fa fa-link"></i>
                    </div>
                </a>
            </div>
            <div class="course-content">
                <h3><a href="course-details.html">@course.Name</a></h3>
                <p>@course.Description</p>
                <a class="default-btn" href="course-details.html">read more</a>
            </div>
        </div>
    </div>
}

FinalProjectasp/FinalProjectasp/Views/Shared/_EventPartial.cshtml
@model List<Event>;
@{
    Layout = null;
}

@foreach (Event ev in Model)
{
    <div class="col-md-4 col-sm-8 col-xs-8">
        <div class="single-event mb-35">
            <div class="event-img">
                <a href="event-details.html"><img src="~/img/event/@ev.Image" alt="event"></a>
            </div>
            <div class="event-content text-left">
                <h3>@ev.Day</h3>
                <h4><a href="event-details.html">@ev.EventName</a></h4>
                <ul>
                    <li><i class="fa fa-clock-o"></i>@ev.StartTime</li>
                    <li><i class="fa fa-map-marker"></i>@ev.Location</li>
                </ul>
                <div class="event-content-right">
                    <a class="default-btn" href="event-details.html">join now</a>
                </div>
            </div>
        </div>
    </div>
}

FinalProjectasp/FinalProjectasp/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<!-- Mirrored from demo.devitems.com/eduhome/index-2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 21 Jun 2020 19:37:50 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Eduhome - Educational HTML Template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!-- Place favicon.ico in the root directory -->

    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/animate.css">
    <link rel="stylesheet" href="~/css/meanmenu.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/et-line-icon.css">
    <link rel="stylesheet" href="~/css/reset.css">
    <link rel="stylesheet" href="~/css/ionicons.min.css">
    <link rel="stylesheet" href="~/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/responsive.css">
    <script src="~/js/vendor/modernizr-2.8.3.min.js"></script>
</head>
<body>
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Header Area Start -->

    <header class="top">
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-8 col-xs-12">
                        <div class="header-top-left">
                            <p>HAVE ANY QUESTION ?  +880 5698  598  6587</p>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-12">
                        <div class="header-top-right text-right">
                            <ul>
                                @if (!User.Identity.IsAuthenticated)
                                {
                                    <li><a asp-controller="Account" asp-action="Login" >Login</a></li>
                                    <li><a asp-controller="Account" asp-action="Register">Sign up</a></li>
                                }
                                else
                                {
                                    <li><a >@User.Identity.Name</a></li>
                                    <li><a asp-controller="Account" asp-action="Logout">Log out</a></li>
                                }

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-area two header-sticky">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-3 col-xs-6">
                        <div class="logo">
                            <a href="index.html"><img src="~/img/logo/logo2.png" alt="eduhome" /></a>
                        </div>
                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-6">
                        <div class="content-wrapper text-right">
                            <!-- Main Menu Start -->
                            <div class="main-menu">
                                <nav>
                                    <ul>
                                        <li>
                                            <a asp-controller="Home" asp-action="Index" >Home</a>
                                          
                                        </li>
                                        <li><a asp-controller="About" asp-action="Index">About</a></li>
                                        <li>
                                            <a asp-controller="Course" asp-action="Index">courses</a>
                                           
                                        </li>
                                        <li>
                                            <a asp-controller="Event" asp-action="Index">event</a>
                                           
                                        </li>
                                        <li class="hidden-sm">
                                            <a asp-controller="Teacher" asp-action="Index">teacher</a>
                                            
                                        </li>
                                        <li>
                                            <a  asp-controller="Blog" asp-action="Index">blog</a>
                                           
                                        </li>
                                        <li><a href="contact.html">Contact</a></li>
                                        <li><a href="#">Buy Now</a>
                                    </ul>
                                </nav>
                            </div>
                            <!--Search Form Start-->
                            <div class="search-btn">
                                <ul data-toggle="dropdown" class="header-search search-toggle">
                                    <li class="search-menu">
                                        <i class="fa fa-search"></i>
                                    </li>
                                </ul>
                                <div class="search">
                                    <div class="search-form">
                                        <form id="search-form" action="#">
                                            <input type="search" placeholder="Search here..." name="search" />
                                            <button type="submit">
                                                <span><i class="fa fa-search"></i></span>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <!--End of Search Form-->
                            <!-- Main Menu End -->
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="mobile-menu hidden-lg hidden-md hidden-sm"></div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    @*@await Component.InvokeAsync("Header");*@

    @RenderBody()
    <footer class="footer-area">
        <div class="main-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="single-widget pr-60">
                            <div class="footer-logo pb-25">
                                <a href="index.html"><img src="~/img/logo/footer-logo.png" alt="eduhome"></a>
                            </div>
                            <p>I must explain to you how all this mistaken idea of denoung pleure and praising pain was born and give you a coete account of the system. </p>
                            <div class="footer-social">
                                <ul>
                                    <li><a href="#"><i class="zmdi zmdi-facebook"></i></a></li>
                                    <li><a href="#"><i class="zmdi zmdi-pinterest"></i></a></li>
                                    <li><a href="#"><i class="zmdi zmdi-vimeo"></i></a></li>
                                    <li><a href="#"><i class="zmdi zmdi-twitter"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="single-widget">
                            <h3>information</h3>
                            <ul>
                                <li><a href="#">addmission</a></li>
                                <li><a href="#">Academic Calender</a></li>
                                <li><a href="event.html">Event List</a></li>
                                <li><a href="#">Hostel &amp; Dinning</a></li>
                                <li><a href="#">TimeTable</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                        <div class="single-widget">
                            <h3>useful links</h3>
                            <ul>
                                <li><a href="course.html">our courses</a></li>
                                <li><a href="about.html">about us</a></li>
                                <li><a href="teacher.html">teachers &amp; faculty</a></li>
                                <li><a href="#">teams &amp; conditions</a></li>
                                <li><a href="event.html">our events</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="single-widget">
                            <h3>get in touch</h3>
                            <p>Your address goes here, Street<br>City, Roadno 785 New York</p>
                            <p>+880  548  986  898  87<br>+880  659  785  658  98</p>
                            <p>info@eduhome.com<br>www.eduhome.com</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom text-center">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <p>Copyright © <a href="#" target="_blank">HasTech</a> 2017. All Right Reserved By Hastech.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    @*@await Component.InvokeAsync("Footer");*@
    <!-- Footer End -->

    <script src="~/js/vendor/jquery-1.12.0.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.meanmenu.js"></script>
    <script src="~/js/jquery.magnific-popup.js"></script>
    <script src="~/js/ajax-mail.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.mb.YTPlayer.js"></script>
    <script src="~/js/jquery.nicescroll.min.js"></script>
    <script src="~/js/plugins.js"></script>
    <script src="~/js/main.js"></script>
</body>

<!-- Mirrored from demo.devitems.com/eduhome/index-2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 21 Jun 2020 19:41:25 GMT -->
</html>

FinalProjectasp/FinalProjectasp/Views/Shared/_TeacherPartial.cshtml
@model List<EduHome.Models.Teacher>;
@{
    Layout = null;
}


@foreach (EduHome.Models.Teacher teacher in Model)
{
    <div class="col-md-3 col-sm-4 col-xs-12">
        <div class="single-teacher">
            <div class="single-teacher-img">
                <a href="teacher-details.html"><img src="img/teacher/@teacher.Image" alt="teacher"></a>
            </div>
            <div class="single-teacher-content text-center">
                <h2><a href="teacher-details.html">@teacher.Name</a></h2>
                <h4>@teacher.Profession</h4>
                <ul>
                    <li><a href="https://www.facebook.com/devitems/?ref=bookmarks"><i class="zmdi zmdi-facebook"></i></a></li>
                    <li><a href="https://www.pinterest.com/devitemsllc/"><i class="zmdi zmdi-pinterest"></i></a></li>
                    <li><a href="#"><i class="zmdi zmdi-vimeo"></i></a></li>
                    <li><a href="https://twitter.com/devitemsllc"><i class="zmdi zmdi-twitter"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
}